### ISSUE TITLE
Does not resolve ~ in db filename

### ISSUE THREAD

**Issue by pandrews11** [brendoncarroll/music_guy#1]
starting app with `node music_guy.js` getting the following error:

```
Patricks-MacBook-Air :: ~/Workspace/music_guy ‹master› » node music_guy.js
Starting Music Guy...
Listening on port 3000 ...
Renamer using %albumartist%/%album%/%title%
/Users/pandrews/Workspace/music_guy/db.js:44
                throw err;
                      ^
Error: ENOENT, no such file or directory '~/Music/_music_guy'
    at Error (native)
    at Object.fs.mkdirSync (evalmachine.<anonymous>:747:18)
    at Db (/Users/pandrews/Workspace/music_guy/db.js:41:16)
    at MusicGuy (/Users/pandrews/Workspace/music_guy/music_guy.js:38:5)
    at Object.<anonymous> (/Users/pandrews/Workspace/music_guy/music_guy.js:53:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I have a directory and a file at that location.

**Comment by brendoncarroll** [comment]
It doesn't resolve '~'.  I can look into this.  Until then just use the full path.
